### ISSUE TITLE
Rendering breaks when cycling fog distance

### ISSUE THREAD

**Issue by HSQuillin** [BlueStaggo/VoxelThing#4]
![image](https://github.com/BlueStaggo/VoxelThing/assets/31800980/708c8f24-1112-4b70-8b7c-04ae406a1879)

When frequently using shift+F to change the fog distance (4 -> 8 -> 16 -> etc.) and cycling through several times, it turns all of the chunks that are rendered within the world to be invisible. It takes up to 30 seconds for the world to render back in afterwards; in other cases, if it doesn't, you will get a `EXCEPTION_PRIV_INSTRUCTION` crash file in your directory. Tested on dev20230828.

Best way I found to reproduce this is to continually walk backwards into a corner while constantly pressing/spamming Shift+F, and repeating until the renderer breaks.

Link to Pastebin - https://pastebin.com/QPPSgTp7

**Comment by BlueStaggo** [comment]
I cannot reproduce this issue and people aren't going to spam Shift+F in normal gameplay anyways.
